// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC39pzHFwKTVXmI4Z7SIxdzZVLqOqlgcQ',
    appId: '1:126042408871:web:b7cc18acd05a78e0e59882',
    messagingSenderId: '126042408871',
    projectId: 'gamesglobalchallenge',
    authDomain: 'gamesglobalchallenge.firebaseapp.com',
    storageBucket: 'gamesglobalchallenge.appspot.com',
    measurementId: 'G-RBH05ER2J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFLy-1gm11ggvm4YPlDTVlIazzGz4RCtI',
    appId: '1:126042408871:android:82819ed403e7f331e59882',
    messagingSenderId: '126042408871',
    projectId: 'gamesglobalchallenge',
    storageBucket: 'gamesglobalchallenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM2WJf30zqFfQ0Ofse1gafPnQVRbQds-4',
    appId: '1:126042408871:ios:bcabecf5619e3e33e59882',
    messagingSenderId: '126042408871',
    projectId: 'gamesglobalchallenge',
    storageBucket: 'gamesglobalchallenge.appspot.com',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM2WJf30zqFfQ0Ofse1gafPnQVRbQds-4',
    appId: '1:126042408871:ios:19de0bcc38db85ece59882',
    messagingSenderId: '126042408871',
    projectId: 'gamesglobalchallenge',
    storageBucket: 'gamesglobalchallenge.appspot.com',
    iosBundleId: 'com.example.hello.RunnerTests',
  );
}
